services:
  postgres:
    container_name: oauth
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rabin
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"